services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_DIR:-./app}:/var/www/html
    networks:
      - backend_network
    depends_on:
      - php
  php:
    build: php
    volumes:
      - ${PROJECT_DIR:-./app}:/var/www/html
      - ./php/xdebug/profiler:/tmp/xdebug_profiler
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=serverName=docker-server
    networks:
      - backend_network
networks:
  backend_network: