services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_DIR:-./app}:/var/www/html
    depends_on:
      - php
  php:
    build: php
    volumes:
      - ${PROJECT_DIR:-./app}:/var/www/html