services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    build: php # Builds from the Dockerfile in the current directory
    volumes:
      - ./app:/var/www/html